services:
  wikijs:
    image: linuxserver/wikijs:latest
    container_name: wikijs
    volumes:
      - wikijs-config:/config
      - wikijs-data:/data
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      TZ: Japan
      PUID: 1000
      GUID: 1000
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_USER: wikijs
      DB_PASS: ${WIKIJS_DB_PASS}
      DB_NAME: wikijs
    depends_on:
      - wikijs-postgres
  postgres:
    image: postgres:16
    container_name: wikijs-postgres
    shm_size: 128mb
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: wikijs
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: wikijs-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - wikijs-postgres
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin-config.json:/pgadmin4/servers.json
  elastic:
    image: elasticsearch:8.14.3
    container_name: wikijs-es
    environment:
      discovery.type: single-node
volumes:
  wikijs-config:
  wikijs-data:
  postgres-data:
  pgadmin-data:
